## Replace "TAG" with the desired face-api version
FROM regulaforensics/face-api:TAG

#CPU version
COPY regula.license /app/extBin/unix_x64/cpu
#GPU version
#COPY regula.license /app/extBin/unix_x64/gpu
